version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started

  redis:
    image: redis:6
    container_name: autenticacion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:13
    container_name: autenticacion-db
    environment:
      POSTGRES_USER: Raphtalia
      POSTGRES_PASSWORD: G4L1L30.30
      POSTGRES_DB: global_speed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: autenticacion-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    container_name: autenticacion-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: autenticacion-redisinsight
    restart: always
    ports:
      - "8001:5540"
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
